### ISSUE TITLE
Sonic cd white screen error

### ISSUE THREAD

**Issue by xddayudaa** [RSDKModding/RSDKv3-Decompilation#244] opened 2024-07-29 21:21 UTC
### Before opening this issue, I ensure that...

- [x] I have read the [FAQ](https://github.com/RSDKModding/RSDKv3-Decompilation/blob/main/FAQ.md) and confirmed my issue is not mentioned in it.
- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
- [X] I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
- [X] This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.

### Expected Behavior

let the game OPEN

### Actual Behavior

the window goes blank and close

### Steps to Reproduce

1.I open the game folder
2.I open the game
3.the window goes blank and closes after about 3 seconds

### Screenshots

![imagen_2024-07-29_181115398](https://github.com/user-attachments/assets/2ef9ebfe-02fa-412e-aa12-98479244ca2d)

### Log File

Couldn't load file 'Data/Scripts/ByteCode/GlobalCode.bin'
Loaded File 'Data/Scripts/ByteCode/GS000.bin'
Loaded File 'Data/Game/GameConfig.bin'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/Sonic CD and Knuckles\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/MegAmisAdditions\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/ShieldsPlus\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/Sonic CD and Knuckles\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/MegAmisAdditions\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/ShieldsPlus\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/Sonic CD and Knuckles\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/MegAmisAdditions\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/ShieldsPlus\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/Sonic CD and Knuckles\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/MegAmisAdditions\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/ShieldsPlus\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/Sonic CD and Knuckles\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/MegAmisAdditions\Data\Game\game.xml'
Loaded File 'C:\Users\quaso\Desktop\SonicCDAndKnuckles\mods/ShieldsPlus\Data\Game\game.xml'

### Decompilation Version

i dont know

### Game Version

Blit Release (Steam/XBOX 360/PS3)

### Game Revision

i dont know

### Renderer Type

Software Renderer

### Platform

windows

### Additional Comments

im spanish

**Comment by MegAmi24** [comment] 2024-07-29 22:00
Duplicate of #243. Closing.

**Closed by MegAmi24** 2024-07-29 22:00 UTC
Labels: bug
